### ISSUE TITLE
Error on terraform install

### ISSUE THREAD

**Issue by Fvegini** [aws-samples/eks-kubeflow-cloudformation-quick-start#74]
I'm trying to follow the workshop guide to install and test kubeflow, but the script is failing. On the first minute of the "30 minutes installation"

![image](https://github.com/aws-samples/aws-deeplearning-labs/assets/32243959/5ccad488-2c8f-4902-8afc-ab64cc1f57b0)

**Comment by amitkalawat** [comment]
Can you try again. This was fixed earlier today.

**Comment by amitkalawat** [comment]
https://github.com/awslabs/kubeflow-manifests/pull/751
